name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global
          sf --version

      - name: Authenticate to Developer Org
        env:
          SFDX_AUTH_URL: ${{ secrets.SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > sfdx_auth_url.txt
          sf org login sfdx-url -f sfdx_auth_url.txt --alias Developer_ORG

      - name: Deploy source to Developer Org
        run: sf project deploy start --target-org Developer_ORG --wait 10

      - name: Run Tests in Developer Org
        run: sf apex run test --target-org Developer_ORG --result-format human --code-coverage --wait 10

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: sf project deploy start --target-org Developer_ORG --manifest manifest/package.xml --wait 10
