name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli --global
          sfdx --version

      - name: Authenticate to Developer Org
        env:
          SFDX_AUTH_URL: ${{ secrets.DEV_ORG_SFDX_AUTH_URL }}
        run: |
          echo "$SFDX_AUTH_URL" > sfdx_auth_url.txt
          sfdx auth:sfdxurl:store -f sfdx_auth_url.txt -a DevOrg

      - name: Push source to Developer Org
        run: sfdx force:source:push -u DevOrg

      - name: Run Tests in Developer Org
        run: sfdx force:apex:test:run -u DevOrg --resultformat human --codecoverage --wait 10

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: sfdx force:source:deploy -u DevOrg -x manifest/package.xml
